# Generated by Django 5.0.7 on 2024-07-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_club', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_club', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_club', to=settings.AUTH_USER_MODEL)),
                ('vice_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
