# Generated by Django 5.0.7 on 2024-07-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_created_by_alter_club_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
