# Generated by Django 5.0.7 on 2024-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinfo',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentinfo',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
